apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::027038266804:role/eksctl-demo-cluster-cluster-FargatePodExecutionRole-Bt5m44sFtw2P
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:node-proxier

  mapUsers: |
    - userarn: arn:aws:iam::027038266804:root
      username: admin
      groups:
        - system:masters
